config-version: 1.2
config:
  doNetherrackDamage:
    enabled: true
    damage: 2
    fire: true
  SoulSandWitherEffect:
    enabled: true
    effectDuration: 150 #in ticks
    effectAmplifier: 1
  doDustInBasalDeltas: true
  doWarpedNyliumLevitation: true